- name: variables to print
  hosts: web
  vars: #play level, sll tasks in this play have access to this
    COURSE: "Devops with AWS"
    DURATION: "220HRS"
    TRAINER: "Haritha"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, iam learning {{COURSE}}, Duration: {{DURATION}}, Trainer: {{TRAINER}}"

  - name: print the information again
    vars: # task level variables
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, iam learning {{COURSE}}, Duration: {{DURATION}}, Trainer: {{TRAINER}}"

  - name: print the information again and again
    ansible.builtin.debug:
      msg: "Hi, iam learning {{COURSE}}, Duration: {{DURATION}}, Trainer: {{TRAINER}}"