- name: devops courses information
  hosts: local
  connection: local # for localhosts
  vars:
    course: "Devops with AWS" #String
    duration: 120 #number
    topics: #list
    - Linux
    - Shell
    - Ansible
    - Terraform
    - AWS
    - K8
    live: true # boolean
    tools: #map/dictionery
      ci: jenkins  # string
      cm: ansible
      cloud: aws
      aws:
      - IAM
      - S3
    tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ course }}, with duration {{ duration }} topics are: {{ topics }}, and live: {{ live }}, tools are {{ tools }}"


